# 应用名称
spring:
  application:
    name: nacos-config-sample-selune.yaml
  # spring 静态资源扫描路径
  resources:
    static-locations: classpath:/static/

# 应用服务 WEB 访问端口
server:
  port: 8080

# Actuator Web 访问端口
management:
  server:
    port: 8081
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
